use bytes::Bytes;

use crate::v1::types::{Permission, oauth::Scope};

/// an http endpoint
pub trait Endpoint {
    type Request: Request;
    type Response: Response;

    /// get the metadata for this endpoint
    fn metadata() -> Metadata;

    /// get the utoipa path item for this request
    #[cfg(feature = "utoipa")]
    fn path_item() -> utoipa::openapi::PathItem;
}

/// Metadata describing an API endpoint.
///
/// This struct is generated by the `#[endpoint]` macro and contains
/// routing and authorization information for the endpoint.
pub struct Metadata {
    /// Unique identifier for this endpoint.
    pub operation_id: &'static str,

    /// One line description of what this endpoint does.
    pub summary: &'static str,

    /// A more comprehensive description of this endpoint.
    pub description: Option<&'static str>,

    /// The HTTP method used by this endpoint.
    pub method: Method,

    /// The URL path pattern for this endpoint (e.g., `/user/{id}`).
    pub path: &'static str,

    /// Tags used for documentation grouping and organization (user-provided only).
    pub tags: &'static [&'static str],

    /// All tags including badge tags (e.g., `badge.scope.Identify`).
    pub tags_full: &'static [&'static str],

    /// Required OAuth scopes for accessing this endpoint.
    pub scopes: &'static [Scope],

    /// Required permissions for accessing this endpoint.
    pub permissions: &'static [Permission],

    /// Optional permissions that may enhance functionality but are not required.
    pub permissions_optional: &'static [Permission],

    /// Required server permissions for accessing this endpoint.
    pub permissions_server: &'static [Permission],

    /// Optional server permissions that may enhance functionality but are not required.
    pub permissions_server_optional: &'static [Permission],

    /// Audit log events that may be created.
    pub audit_log_events: &'static [&'static str],
}

/// HTTP method for an endpoint.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Method {
    Get,
    Post,
    Put,
    Patch,
    Delete,
    Head,
}

pub trait Request: Sized {
    /// encode this into an http request
    fn encode(self) -> http::Request<Bytes>;

    /// extract this from an http request
    ///
    /// on failure, returns the original http request
    fn extract(req: http::Request<Bytes>) -> Result<Self, http::Request<Bytes>>;
}

pub trait Response: Sized {
    /// encode this into an http response
    fn encode(self) -> http::Response<Bytes>;

    /// extract this from an http response
    ///
    /// on failure, returns the original http response
    fn extract(req: http::Response<Bytes>) -> Result<Self, http::Response<Bytes>>;
}
