-- with role_json as (
--     select room_id, user_id, coalesce(array_agg(role.*), '{}') as "roles!: Vec<crate::types::Role>"
--     from role_member
--     join role on role_member.role_id = role.id
--     group by room_id, user_id
-- )
-- select
--     r.room_id, r.override_name, r.override_description,
--     r.membership as "membership: _",
--     row_to_json(usr) as "user!: crate::types::User",
--     "roles!: Vec<crate::types::Role>"
-- from room_member as r
-- join usr on usr.id = r.user_id
-- left join role_json on role_json.user_id = r.user_id
--  and role_json.room_id = r.room_id
-- where usr.id = $1 and r.room_id = $2
