use proc_macro2::{Span, TokenStream};
use quote::quote;
use syn::{parse2, spanned::Spanned, Attribute, Fields, Ident, Item, ItemMod, ItemStruct, LitStr};

use crate::parse::{EndpointArgs, EndpointField, FieldKind};

pub fn expand(args: TokenStream, item: TokenStream) -> syn::Result<TokenStream> {
    let args: EndpointArgs = parse2(args)?;
    let module: ItemMod = parse2(item)?;

    let mod_name = &module.ident;
    let mod_vis = &module.vis;
    let mod_attrs = module.attrs.iter().filter(|a| a.path().is_ident("doc"));

    let items = module
        .content
        .as_ref()
        .map(|(_, items)| items.as_slice())
        .unwrap_or(&[]);

    // Extract Request and Response structs
    let request_struct = find_struct(items, "Request")?;
    let response_struct = find_struct(items, "Response")?;

    let req_fields = extract_fields(request_struct)?;
    let resp_fields = extract_fields(response_struct)?;

    // --- Build utoipa path params list ---
    let _path_params: Vec<TokenStream> = req_fields
        .iter()
        .filter(|f| matches!(f.kind, FieldKind::Path(_)))
        .map(|f| {
            let name = match &f.kind {
                FieldKind::Path(Some(n)) => n.clone(),
                _ => f.ident.to_string(),
            };
            let _ty = &f.ty;
            quote! { (#name, description = "") }
        })
        .collect();

    // --- Build badges from scopes/permissions ---
    let mut tags: Vec<LitStr> = args.tags.clone();
    for s in &args.scopes {
        let badge = LitStr::new(&format!("badge.scope.{}", s.value()), s.span());
        tags.push(badge);
    }
    for p in &args.permissions {
        let badge = LitStr::new(&format!("badge.perm.{}", p.value()), p.span());
        tags.push(badge);
    }
    for p in &args.permissions_optional {
        let badge = LitStr::new(&format!("badge.perm-opt.{}", p.value()), p.span());
        tags.push(badge);
    }

    // --- Build utoipa response annotations ---
    let _utoipa_responses: Vec<TokenStream> = args
        .responses
        .iter()
        .map(|r| {
            let status = &r.status;
            let desc = r
                .description
                .as_ref()
                .map(|d| d.value())
                .unwrap_or_default();
            match &r.body {
                Some(ty) => quote! { (status = #status, body = #ty, description = #desc) },
                None => quote! { (status = #status, description = #desc) },
            }
        })
        .collect();

    let _method = &args.method;
    let _path = &args.path;

    // --- Build Request struct (cleaned, no lamprey attrs) ---
    let request_clean = build_clean_struct(request_struct, &req_fields)?;
    let response_clean = build_clean_struct(response_struct, &resp_fields)?;

    // --- Build FromRequest / IntoResponse impls ---
    let _request_from_parts = build_request_extractor(&req_fields, mod_name);
    let _response_into = build_response_into(&resp_fields);

    let expanded = quote! {
        #(#mod_attrs)*
        #mod_vis mod #mod_name {
            use super::*;

            #[derive(Debug)]
            #request_clean

            #[derive(Debug)]
            #response_clean

            // utoipa path registration helper — call this from routes()
            pub fn __utoipa_path() -> utoipa::openapi::path::PathItem {
                // generated by utoipa macro (see __handler module)
                todo!()
            }
        }

        // utoipa annotation lives outside the module so it can reference handler fn
        // The handler macro will emit this; we just record metadata here.
        const _: () = {
            // compile-time check that scopes/permissions are valid strings
            #(let _ = #tags;)*
        };
    };

    Ok(expanded)
}

fn find_struct<'a>(items: &'a [Item], name: &str) -> syn::Result<&'a ItemStruct> {
    items
        .iter()
        .find_map(|item| {
            if let Item::Struct(s) = item {
                if s.ident == name {
                    return Some(s);
                }
            }
            None
        })
        .ok_or_else(|| {
            syn::Error::new(
                Span::call_site(),
                format!("endpoint module must contain a `{name}` struct"),
            )
        })
}

fn extract_fields(s: &ItemStruct) -> syn::Result<Vec<EndpointField>> {
    let fields = match &s.fields {
        Fields::Named(f) => &f.named,
        _ => {
            return Err(syn::Error::new(
                s.span(),
                "Request/Response must have named fields",
            ))
        }
    };

    fields
        .iter()
        .map(|f| {
            let ident = f.ident.clone().unwrap();
            let ty = f.ty.clone();
            let kind = extract_field_kind(&f.attrs, &ident)?;
            let doc = f
                .attrs
                .iter()
                .filter(|a| a.path().is_ident("doc"))
                .cloned()
                .collect();
            Ok(EndpointField {
                kind,
                ident,
                ty,
                doc,
            })
        })
        .collect()
}

fn extract_field_kind(attrs: &[Attribute], ident: &Ident) -> syn::Result<FieldKind> {
    for attr in attrs {
        let path = attr.path();
        if path.is_ident("path") {
            let override_name = try_parse_str_arg(attr);
            return Ok(FieldKind::Path(override_name));
        }
        if path.is_ident("query") {
            let override_name = try_parse_str_arg(attr);
            return Ok(FieldKind::Query(override_name));
        }
        if path.is_ident("header") {
            let override_name = try_parse_str_arg(attr);
            return Ok(FieldKind::Header(override_name));
        }
        if path.is_ident("json") {
            return Ok(FieldKind::Json);
        }
    }
    Err(syn::Error::new(
        ident.span(),
        "field must have one of: #[path], #[query], #[header], #[json]",
    ))
}

fn try_parse_str_arg(attr: &Attribute) -> Option<String> {
    attr.parse_args::<LitStr>().ok().map(|s| s.value())
}

fn build_clean_struct(original: &ItemStruct, fields: &[EndpointField]) -> syn::Result<TokenStream> {
    let name = &original.ident;
    let vis = &original.vis;
    let cleaned: Vec<TokenStream> = fields
        .iter()
        .map(|f| {
            let doc = &f.doc;
            let ident = &f.ident;
            let ty = &f.ty;
            let field_vis = &original
                .fields
                .iter()
                .find(|of| of.ident.as_ref() == Some(ident))
                .map(|of| of.vis.clone())
                .unwrap_or(syn::Visibility::Inherited);
            quote! {
                #(#doc)*
                #field_vis #ident: #ty,
            }
        })
        .collect();
    Ok(quote! {
        #vis struct #name {
            #(#cleaned)*
        }
    })
}

fn build_request_extractor(fields: &[EndpointField], _mod_name: &Ident) -> TokenStream {
    // Generates axum extractor logic — used by handler macro
    // Returns code that destructures path/query/json from axum extractors
    let mut path_fields = vec![];
    let mut query_fields = vec![];
    let mut json_fields = vec![];

    for f in fields {
        match &f.kind {
            FieldKind::Path(_) => path_fields.push(f),
            FieldKind::Query(_) => query_fields.push(f),
            FieldKind::Json => json_fields.push(f),
            FieldKind::Header(_) => {}
        }
    }
    // actual extractor impl emitted by handler macro which has access to State type
    quote! {}
}

fn build_response_into(_fields: &[EndpointField]) -> TokenStream {
    quote! {}
}
