// WORK IN PROGRESS PLANNING

use lamprey_macros::record;

use crate::v2::types::MediaTrackId;

// TODO: add tracks field to media
// maybe not even the full track list, just a has tracks flag?
// though i probably do need to at least send the thumbnail metadata

#[record]
pub struct TrackCreate {
    // option to generate, upload, etc
    #[serde(rename = "type")]
    pub ty: TrackType,
    pub lang: Option<String>,
    pub label: Option<String>,
}

#[record]
pub struct TrackUpdate {
    /// the type of a track
    ///
    /// only valid transition is subtitles to/from captions
    #[serde(rename = "type")]
    pub ty: Option<TrackType>,
    pub lang: Option<Option<String>>,
    pub label: Option<Option<String>>,
}

/// an extra file for a piece of media
#[record]
pub struct Track {
    pub id: MediaTrackId,
    pub source: TrackSource,

    /// the type of this track
    #[serde(rename = "type")]
    pub ty: TrackType,

    /// the language of a track
    #[schema(max_length = 64)]
    #[validate(length(max = 64))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lang: Option<String>,

    /// a human readable name for a track
    #[schema(max_length = 64)]
    #[validate(length(max = 64))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,

    /// file size in bytes
    pub size: u64,
}

/// where a track came from
#[record]
#[serde(tag = "type")]
pub enum TrackSource {
    /// embedded in the source file
    Embedded,

    // /// manually uploaded
    // Uploaded,

    // /// another piece of media attached to this one
    // Attached { media_id: MediaId },
    /// generated by the server
    Generated {
        generator_name: String,
        generator_version: String,
    },
}

/// the type of a track
#[record]
#[derive(Copy, PartialEq, Eq)]
pub enum TrackType {
    /// transcription of spoken text; lyrics
    ///
    /// formatted as webvtt
    Subtitles,

    /// transcription incluing relevant sound effects
    ///
    /// formatted as webvtt
    Captions,
    // TODO: thumbnail, chapters, audio
}

// TODO: message sync media track create/update/delete?

// TODO: error type for tracks?
// #[record]
// #[derive(thiserror::Error)]
// pub enum Error {
//     // cannot generate track
//     // default thumbnail cannot be deleted
//     // embedded track cannot be deleted
//     // thumbnails must be in a known image format
//     // captions must be encoded in webvtt
//     // subtitles must be encoded in webvtt
// }
