use super::Permission;

/// Which permissions are granted to someone with Admin in a room
pub const ADMIN_ROOM: &[Permission] = &[
    Permission::Admin,
    Permission::BypassSlowmode,
    Permission::CalendarEventCreate,
    Permission::CalendarEventManage,
    Permission::CalendarEventRsvp,
    Permission::ChannelEdit,
    Permission::ChannelManage,
    Permission::EmojiManage,
    Permission::EmojiUseExternal,
    Permission::IntegrationsManage,
    Permission::InviteCreate,
    Permission::InviteManage,
    Permission::MemberBan,
    Permission::MemberBridge,
    Permission::MemberKick,
    Permission::MemberNickname,
    Permission::MemberNicknameManage,
    Permission::MemberTimeout,
    Permission::MessageAttachments,
    Permission::MessageCreate,
    Permission::MessageCreateThread,
    Permission::MessageDelete,
    Permission::MessageEmbeds,
    Permission::MessageMassMention,
    Permission::MessageMove,
    Permission::MessagePin,
    Permission::MessageRemove,
    Permission::ReactionAdd,
    Permission::ReactionPurge,
    Permission::RoleApply,
    Permission::RoleManage,
    Permission::RoomManage,
    Permission::ServerMetrics,
    Permission::ServerOversee,
    Permission::ServerReports,
    Permission::TagApply,
    Permission::TagManage,
    Permission::ThreadCreatePrivate,
    Permission::ThreadCreatePublic,
    Permission::ThreadEdit,
    Permission::ThreadLock,
    Permission::ThreadManage,
    Permission::ThreadManage,
    Permission::ViewAnalytics,
    Permission::ViewAuditLog,
    Permission::ViewChannel,
    Permission::VoiceBroadcast,
    Permission::VoiceConnect,
    Permission::VoiceDeafen,
    Permission::VoiceDisconnect,
    Permission::VoiceMove,
    Permission::VoiceMute,
    Permission::VoicePriority,
    Permission::VoiceRequest,
    Permission::VoiceSpeak,
    Permission::VoiceVad,
    Permission::VoiceVideo,
    Permission::DocumentCreate,
    Permission::DocumentEdit,
    Permission::DocumentComment,
];

/// Which permissions are granted to someone with Admin in a thread
///
/// Some of these might be unintentionally re-added (eg. EmojiUseExternal), but
/// thats what Admin is supposed to do
pub const ADMIN_THREAD: &[Permission] = &[
    Permission::Admin,
    Permission::BypassSlowmode,
    Permission::CalendarEventCreate,
    Permission::CalendarEventManage,
    Permission::CalendarEventRsvp,
    Permission::ChannelEdit,
    Permission::EmojiUseExternal,
    Permission::IntegrationsManage,
    Permission::InviteCreate,
    Permission::InviteManage,
    Permission::MemberBan,
    Permission::MemberBridge,
    Permission::MemberKick,
    Permission::MemberNickname,
    Permission::MemberNicknameManage,
    Permission::MemberTimeout,
    Permission::MessageAttachments,
    Permission::MessageCreate,
    Permission::MessageCreateThread,
    Permission::MessageDelete,
    Permission::MessageEmbeds,
    Permission::MessageMassMention,
    Permission::MessageMove,
    Permission::MessagePin,
    Permission::MessageRemove,
    Permission::ReactionAdd,
    Permission::ReactionAdd,
    Permission::ReactionPurge,
    Permission::TagApply,
    Permission::ThreadEdit,
    Permission::ThreadLock,
    Permission::ThreadManage,
    Permission::ThreadManage,
    Permission::ViewChannel,
    Permission::VoiceBroadcast,
    Permission::VoiceConnect,
    Permission::VoiceDeafen,
    Permission::VoiceDisconnect,
    Permission::VoiceMove,
    Permission::VoiceMute,
    Permission::VoicePriority,
    Permission::VoiceRequest,
    Permission::VoiceSpeak,
    Permission::VoiceVad,
    Permission::VoiceVideo,
    Permission::DocumentCreate,
    Permission::DocumentEdit,
    Permission::DocumentComment,
];

/// Default permissions for everyone in a trusted room (eg. with friends)
pub const EVERYONE_TRUSTED: &[Permission] = &[
    Permission::IntegrationsManage,
    Permission::EmojiUseExternal,
    Permission::InviteCreate,
    Permission::MessageCreate,
    Permission::MessageEmbeds,
    Permission::MessageMassMention, // maybe?
    Permission::MessageAttachments,
    Permission::MessageMove, // maybe?
    Permission::MessagePin,  // maybe?
    Permission::ReactionAdd,
    Permission::MemberNickname,
    Permission::TagApply,
    // Permission::TagManage, // maybe?
    Permission::ThreadCreatePublic,
    Permission::ThreadCreatePrivate,
    Permission::ThreadEdit, // maybe?
    Permission::ViewChannel,
    // Permission::ThreadPin, // maybe?
    // Permission::ThreadPublish, // maybe?
    Permission::ViewAuditLog, // maybe?
    Permission::VoiceConnect,
    Permission::VoiceSpeak,
    Permission::VoiceVideo,
    Permission::VoiceVad,
    Permission::VoiceRequest,
    Permission::MessageCreateThread,
    Permission::BypassSlowmode,
    Permission::CalendarEventCreate,
    Permission::CalendarEventRsvp,
    Permission::ChannelEdit,
    Permission::DocumentCreate,
    Permission::DocumentEdit,
    Permission::DocumentComment,
];

/// Default permissions for everyone in an untrusted room (eg. public)
pub const EVERYONE_UNTRUSTED: &[Permission] = &[
    Permission::EmojiUseExternal,
    Permission::InviteCreate,
    Permission::MessageCreate,
    Permission::MessageEmbeds,
    Permission::MessageAttachments,
    Permission::ReactionAdd,
    Permission::MemberNickname,
    Permission::TagApply, // maybe?
    Permission::ThreadCreatePublic,
    Permission::ThreadCreatePrivate,
    Permission::ThreadEdit, // maybe?
    Permission::ViewChannel,
    // Permission::ViewAuditLog, // maybe?
    Permission::VoiceConnect,
    Permission::VoiceSpeak,
    Permission::VoiceVideo,
    Permission::VoiceVad,
    Permission::VoiceRequest,
    Permission::MessageCreateThread,
    Permission::BypassSlowmode,
    Permission::CalendarEventCreate,
    Permission::CalendarEventRsvp,
    // Permission::DocumentCreate, // maybe
    // Permission::DocumentEdit,   // maybe
    Permission::DocumentComment,
];

/// extra permissions for someone who moderates stuff
pub const MODERATOR: &[Permission] = &[
    Permission::InviteManage,
    Permission::MemberBan,
    Permission::MemberKick,
    Permission::MemberNicknameManage,
    Permission::MemberTimeout,
    Permission::MessageDelete,
    Permission::MessageMove,
    Permission::MessagePin, // maybe?
    Permission::MessageRemove,
    Permission::ReactionPurge,
    Permission::RoleApply, // maybe?
    Permission::TagApply,
    // Permission::TagManage, // maybe?
    Permission::ThreadManage,
    Permission::ThreadEdit,
    Permission::ThreadLock,
    Permission::ThreadManage, // maybe?
    Permission::ViewChannel,
    Permission::ViewAuditLog, // maybe?
    Permission::VoiceDeafen,
    Permission::VoiceDisconnect,
    Permission::VoiceMove,
    Permission::VoiceMute,
    Permission::VoicePriority, // maybe?
    Permission::VoiceVad,
    Permission::VoiceBroadcast,
    Permission::MessageCreateThread,
    Permission::BypassSlowmode,
    Permission::CalendarEventCreate,
    Permission::CalendarEventManage,
    Permission::CalendarEventRsvp,
    Permission::DocumentCreate,
    Permission::DocumentEdit,
    Permission::DocumentComment,
];
