name: build
on:
  push:
    branches:
      - master
jobs:
  populate-cache:
    runs-on: nix
    strategy:
      matrix:
        derivation: ["backend", "backend-oci", "bridge-discord", "bridge-discord-oci"]
    steps:
      - name: setup
        run: |
          git clone https://tezlm:${{secrets.TOKEN}}@git.celery.eu.org/cetahe/cetahe .
          attic login central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
          attic use actions
      - name: build
        run: |
          nix build .#${{matrix.derivation}} -L |& cat
      - name: push
        run: |
          attic push actions result --ignore-upstream-cache-filter
  build-containers:
    runs-on: nix
    needs:
      - populate-cache
    strategy:
      matrix:
        derivation: ["backend", "bridge-discord"]
    steps:
      - name: setup
        run: |
          git clone https://tezlm:${{secrets.TOKEN}}@git.celery.eu.org/cetahe/cetahe .
          docker login git-celery.eu.org --password ${{secrets.TOKEN}}
          attic login central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
          attic use actions
      - name: build
        run: |
          nix build .#${{matrix.derivation}}-oci -L |& cat
      - name: push
        run: |
          ./result | docker load
          docker tag ${{matrix.derivation}}:latest git.celery.eu.org/cetahe/cetahe-${{matrix.derivation}}:latest
          docker push git.celery.eu.org/cetahe/cetahe-${{matrix.derivation}}:latest
