name: build
on:
  push:
    branches:
      - master
jobs:
  backend:
    runs-on: nix
    steps:
      - name: clone
        run: git clone https://tezlm:${{secrets.TOKEN}}@git.celery.eu.org/cetahe/cetahe .
      - name: cache login
        run: attic login central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
      - name: cache setup
        run: attic use actions
      - name: build
        run: nix build .#backend -L --extra-substituters ${{vars.ATTIC_URL}} --extra-trusted-public-keys ${{vars.ATTIC_PUBKEY}} |& cat
      - name: cache push
        run: attic push actions result --ignore-upstream-cache-filter
  backend-oci:
    runs-on: nix
    needs:
      - backend
    steps:
      - name: clone
        run: git clone https://tezlm:${{secrets.TOKEN}}@git.celery.eu.org/cetahe/cetahe .
      - name: cache login
        run: attic login central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
      - name: cache setup
        run: attic use actions
      - name: build
        run: nix build .#backend -L --extra-substituters ${{vars.ATTIC_URL}} --extra-trusted-public-keys ${{vars.ATTIC_PUBKEY}} |& cat
      - name: cache push
        run: attic push actions result --ignore-upstream-cache-filter
  bridge-discord:
    runs-on: nix
    steps:
      - name: clone
        run: git clone https://tezlm:${{secrets.TOKEN}}@git.celery.eu.org/cetahe/cetahe .
      - name: cache login
        run: attic login central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
      - name: cache setup
        run: attic use actions
      - name: build
        run: nix build .#backend -L --extra-substituters ${{vars.ATTIC_URL}} --extra-trusted-public-keys ${{vars.ATTIC_PUBKEY}} |& cat
      - name: cache push
        run: attic push actions result --ignore-upstream-cache-filter
  bridge-discord-oci:
    runs-on: nix
    needs:
      - bridge-discord
    steps:
      - name: clone
        run: git clone https://tezlm:${{secrets.TOKEN}}@git.celery.eu.org/cetahe/cetahe .
      - name: cache login
        run: attic login central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
      - name: cache setup
        run: attic use actions
      - name: build
        run: nix build .#backend -L --extra-substituters ${{vars.ATTIC_URL}} --extra-trusted-public-keys ${{vars.ATTIC_PUBKEY}} |& cat
      - name: cache push
        run: attic push actions result --ignore-upstream-cache-filter
