name: build
on:
  push:
    branches:
      - master
jobs:
  populate-cache-deps:
    runs-on: nix
    container:
      volumes: actions_nix_store:/nix/store
    strategy:
      matrix:
        derivation: ["cargo-deps"]
    steps:
      - name: setup
        run: |
          attic login --set-default central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
          attic use actions
      - name: build
        run: |
          nix build git+https://git.celery.eu.org/cetahe/cetahe#${{matrix.derivation}} -L |& cat
      - name: push
        run: |
          attic push actions result --ignore-upstream-cache-filter
  populate-cache:
    runs-on: nix
    container:
      volumes: actions_nix_store:/nix/store
    needs:
      - populate-cache-deps
    strategy:
      matrix:
        derivation: [
          "backend",
          "backend-oci",
          "bridge-discord",
          "bridge-discord-oci",
        ]
    steps:
      - name: setup
        run: |
          attic login --set-default central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
          attic use actions
      - name: build
        run: |
          nix build git+https://git.celery.eu.org/cetahe/cetahe#${{matrix.derivation}} -L |& cat
      - name: push
        run: |
          attic push actions result --ignore-upstream-cache-filter
  build-containers:
    runs-on: nix
    container:
      volumes: actions_nix_store:/nix/store
    needs:
      - populate-cache
    strategy:
      matrix:
        derivation: ["backend", "bridge-discord"]
    steps:
      - name: setup
        run: |
          podman login git.celery.eu.org --password ${{secrets.TOKEN}} --username tezlm
          attic login --set-default central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
          attic use actions
      - name: build
        run: |
          nix build git+https://git.celery.eu.org/cetahe/cetahe#${{matrix.derivation}}-oci -L |& cat
      - name: push
        run: |
          ./result | podman load
          podman tag ${{matrix.derivation}}:latest git.celery.eu.org/cetahe/cetahe-${{matrix.derivation}}:latest
          podman push git.celery.eu.org/cetahe/cetahe-${{matrix.derivation}}:latest
