---
name: build
on:
  push:
    branches:
      - master
jobs:
  populate-cache-deps:
    runs-on: docker
    container:
      image: git.celery.eu.org/tezlm/nix-builder
      volumes:
        - actions_nix_store:/nix
    strategy:
      matrix:
        derivation:
          - cargo-deps
    steps:
      - name: setup
        run: |
          attic login --set-default central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
          attic use actions
      - name: build
        run: |
          nix build git+https://git.celery.eu.org/lamprey/lamprey#${{matrix.derivation}} -L |& cat
      - name: push
        run: |
          attic push actions result --ignore-upstream-cache-filter
  populate-cache:
    runs-on: docker
    container:
      image: git.celery.eu.org/tezlm/nix-builder
      volumes:
        - actions_nix_store:/nix
    needs:
      - populate-cache-deps
    strategy:
      matrix:
        derivation:
          - backend
          - backend-oci
          - bridge-discord
          - bridge-discord-oci
          - sfu
          - sfu-oci
          - cdn
          - cdn-oci
    steps:
      - name: setup
        run: |
          attic login --set-default central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
          attic use actions
      - name: build
        run: |
          nix build git+https://git.celery.eu.org/lamprey/lamprey#${{matrix.derivation}} -L |& cat
      - name: push
        run: |
          attic push actions result --ignore-upstream-cache-filter
  push-containers:
    runs-on: docker
    container:
      image: git.celery.eu.org/tezlm/nix-builder
      volumes:
        - actions_nix_store:/nix
    needs:
      - populate-cache
    strategy:
      matrix:
        derivation:
          - backend
          - bridge-discord
          - sfu
          - cdn
    steps:
      - name: setup
        run: |
          nix run nixpkgs#podman -- login git.celery.eu.org --password ${{secrets.TOKEN}} --username tezlm
          attic login --set-default central ${{vars.ATTIC_URL}} ${{secrets.ATTIC_TOKEN}}
          attic use actions
      - name: build
        run: |
          nix build git+https://git.celery.eu.org/lamprey/lamprey#${{matrix.derivation}}-oci -L |& cat
      - name: push
        run: |
          ./result | nix run -- nixpkgs#podman load
          nix run nixpkgs#podman -- tag ${{matrix.derivation}}:latest git.celery.eu.org/lamprey/lamprey-${{matrix.derivation}}:latest
          nix run nixpkgs#podman -- push git.celery.eu.org/lamprey/lamprey-${{matrix.derivation}}:latest
