[package]
name = "lamprey-script"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
async-trait = "0.1.92"
bytes = "1.12.1"
common = { package = "lamprey-common", version = "0.1.0", path = "../crate-common", features = ["utoipa", "validator"] }
cpu-time = "1.0.0"
dashmap = "6.2.1"
http = "1.5.0"
nanoid = "0.5.0"
rquickjs = { version = "0.12.2", features = ["futures", "loader", "macro", "parallel"], optional = true }
rquickjs-serde = "0.6.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "time"] }
tracing = "0.1.44"
validator = "0.20.0"
wasmtime = { version = "44.0.3", optional = true }
lamprey-hakari = { version = "0.1", path = "../crate-hakari" }

[features]
# default = ["javascript"]
default = ["javascript", "wasm"]
javascript = ["dep:rquickjs"]
wasm = ["dep:wasmtime"]
