[package]
name = "kerosene"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
axum = "0.8.9"
clap = { version = "4.6.6", features = ["derive"] }
figment = { version = "0.10.19", features = ["env", "toml"] }
kerosene-core = { version = "0.1.1", path = "../kerosene-core" }
kerosene-rest = { version = "0.1.1", path = "../kerosene-rest" }
kerosene-services = { version = "0.1.1", path = "../kerosene-services" }
kerosene-sync = { version = "0.1.1", path = "../kerosene-sync" }
lamprey = { package = "lamprey-common", version = "0.1.4", path = "../crate-common" }
lamprey-backend-core = { version = "0.1.1", path = "../crate-backend-core" }
opentelemetry = "0.32.0"
opentelemetry-otlp = "0.32.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
