[package]
name = "kerosene-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

[dependencies]
async-trait = "0.1.92"
axum = "0.8.9"
bitflags = "2.13.2"
bytes = { version = "1.12.1", features = ["serde"] }
crc32fast = "1.5.2"
http = "1.5.0"
ipnet = { version = "2.12.2", features = ["serde"] }
lamprey = { package = "lamprey-common", version = "0.1.1", path = "../crate-common" }
opentelemetry = "0.30.0"
opentelemetry-otlp = { version = "0.30.0", features = ["grpc-tonic", "logs", "metrics", "reqwest", "tokio", "tracing", "trace"], default-features = false }
opentelemetry_sdk = { version = "0.30.0", features = ["rt-tokio", "tokio"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.20"
time = "0.3.55"
tokio = { version = "1.53.1", features = ["process"] }
tracing = "0.1.44"
tracing-opentelemetry = "0.31.0"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
unicode-properties = "0.1.4"
unicode-segmentation = "1.13.3"
url = "2.5.8"
utoipa = { version = "5.5.0", features = ["axum_extras", "url", "uuid"] }
uuid = "1.27.0"
