import type { JSX } from "solid-js/jsx-runtime";
import { createMemo, For, on, onCleanup } from "solid-js";
import { type Accessor, createEffect, createSignal } from "solid-js";
import { createStore } from "solid-js/store";

// TODO: split magic numbers into consts, find out how to calculate them

const OVERSCAN = 5;
// const ESTIMATED_H = 24;
const ESTIMATED_H = 80;

export function createList2<T extends { id: string; class?: string }>(options: {
	items: Accessor<Array<T>>;
	autoscroll?: Accessor<boolean>;
	onPaginate?: (dir: "forwards" | "backwards") => void;
	onRestore?: () => boolean;
	isLoading?: Accessor<boolean>;
	containerRef?: Accessor<HTMLElement | undefined>;
}) {
	const [scrollPos, setScrollPos] = createSignal(0);
	const [isAtBottom, setIsAtBottom] = createSignal(true);
	const [visibleRange, setVisibleRange] = createSignal({ start: 0, end: 0 });

	let wrapperEl: HTMLElement | undefined;
	let containerEl: HTMLDivElement | undefined;

	// --- height + offset tracking ---
	const [heights, setHeights] = createStore<Record<string, number>>({});

	const offsets = createMemo(() => {
		const h = heights;
		const items = options.items();
		const result = [0];
		for (let i = 1; i < items.length; i++) {
			const prevH = h[items[i - 1].id] ?? ESTIMATED_H;
			result[i] = result[i - 1] + prevH;
		}
		return result;
	});

	const totalHeight = createMemo(() => {
		const items = options.items();
		const lastIdx = items.length - 1;
		if (lastIdx < 0) return 0;
		return offsets()[lastIdx] + (heights[items[lastIdx].id] ?? ESTIMATED_H);
	});

	// --- ResizeObserver for height correction ---
	let isProgrammaticScroll = false;
	const ro = new ResizeObserver((entries) => {
		if (!wrapperEl) return;
		let heightDiff = 0;
		const firstVisibleIdx = visibleRange().start;
		let changed = false;

		for (const entry of entries) {
			const target = entry.target as HTMLElement;
			const id = target.dataset.id!;
			const newH = Math.round(
				entry.borderBoxSize?.[0]?.blockSize ??
					target.getBoundingClientRect().height,
			);
			const oldH = heights[id] ?? ESTIMATED_H;

			if (newH > 0 && oldH !== newH) {
				setHeights(id, newH);
				changed = true;

				const idx = options.items().findIndex((x) => x.id === id);
				// If item's height changes and it's ABOVE the fold, we must push the scroll down
				// to prevent the viewport from visually jumping!
				if (idx !== -1 && idx < firstVisibleIdx) {
					heightDiff += newH - oldH;
				}
			}
		}

		if (heightDiff !== 0) {
			wrapperEl.scrollTop += heightDiff;
		}
		if (changed) updateRender();
	});

	// --- visible range ---
	function getVisibleRange(): { start: number; end: number } {
		if (!wrapperEl) return { start: 0, end: 0 };
		const items = options.items();
		const scrollTop = wrapperEl.scrollTop;
		const viewportH = wrapperEl.clientHeight;
		const top = scrollTop - OVERSCAN * ESTIMATED_H;
		const bottom = scrollTop + viewportH + OVERSCAN * ESTIMATED_H;

		// binary search start
		let lo = 0, hi = items.length - 1;
		while (lo < hi) {
			const mid = (lo + hi) >> 1;
			if (
				(offsets()[mid] ?? 0) + (heights[items[mid].id] ?? ESTIMATED_H) < top
			) {
				lo = mid + 1;
			} else hi = mid;
		}
		const start = lo;

		lo = start;
		hi = items.length - 1;
		while (lo < hi) {
			const mid = (lo + hi + 1) >> 1;
			if ((offsets()[mid] ?? 0) > bottom) hi = mid - 1;
			else lo = mid;
		}
		return { start, end: lo };
	}

	// --- render loop ---
	function updateRender() {
		if (!wrapperEl || !containerEl) return;
		const { start, end } = getVisibleRange();
		setVisibleRange({ start, end });
	}

	// --- scroll handler ---
	let ticking = false;
	function onScroll() {
		if (isProgrammaticScroll) {
			isProgrammaticScroll = false;
			return;
		}

		if (!wrapperEl) return;
		const pos = wrapperEl.scrollTop;
		const bottom = wrapperEl.scrollHeight - wrapperEl.clientHeight;
		setScrollPos(pos);
		setIsAtBottom(pos >= bottom - 32);

		if (!ticking) {
			ticking = true;
			requestAnimationFrame(() => {
				updateRender();
				if (!options.isLoading?.()) {
					if (pos < 200) options.onPaginate?.("backwards");
					if (bottom - pos < 200) options.onPaginate?.("forwards");
				}
				ticking = false;
			});
		}
	}

	// --- items change (the critical part) ---
	let prevItems: Array<T> = [];

	function onItemsChange(newItems: Array<T>) {
		if (!wrapperEl) {
			prevItems = newItems;
			return;
		}

		const prevLen = prevItems.length;
		const newLen = newItems.length;

		// Skip fixed IDs generated by renderTimeline to reliably find a "real" pivot
		const ignoreIds = new Set([
			"spacer-top",
			"thread-header",
			"spacer-bottom",
			"spacer-bottom-mini",
		]);

		let pivotPrevIdx = -1;
		let pivotNewIdx = -1;
		let isSameList = false;

		for (let i = 0; i < prevLen; i++) {
			if (
				!ignoreIds.has(prevItems[i].id) &&
				!prevItems[i].id.startsWith("divider-")
			) {
				pivotPrevIdx = i;
				pivotNewIdx = newItems.findIndex((x) => x.id === prevItems[i].id);
				if (pivotNewIdx !== -1) {
					isSameList = true;
					break;
				}
			}
		}

		if (isSameList) {
			let oldPivotOffset = 0;
			for (let i = 0; i < pivotPrevIdx; i++) {
				oldPivotOffset += heights[prevItems[i].id] ?? ESTIMATED_H;
			}

			let newPivotOffset = 0;
			for (let i = 0; i < pivotNewIdx; i++) {
				newPivotOffset += heights[newItems[i].id] ?? ESTIMATED_H;
			}

			// This represents how much the pivot item moved mathematically.
			const shiftDiff = newPivotOffset - oldPivotOffset;

			if (shiftDiff !== 0) {
				// Prepended! Offset shifted, sync scroll
				wrapperEl.scrollTop += shiftDiff;
			} else if (newLen > prevLen) {
				// Appended! Lock auto-scroll to bottom if needed
				const wasAtBottom = isAtBottom();
				if (wasAtBottom && options.autoscroll?.()) {
					queueMicrotask(() =>
						wrapperEl?.scrollTo({ top: wrapperEl.scrollHeight })
					);
				}
			}
		} else {
			// Complete channel clear/reload
			setHeights({});
			if (options.onRestore) {
				setTimeout(() => options.onRestore!(), 0);
			}
		}

		prevItems = newItems;
		updateRender();
	}

	return {
		scrollPos,
		isAtBottom,
		scrollBy(pos: number, smooth = false) {
			wrapperEl?.scrollBy({
				top: pos,
				behavior: smooth ? "smooth" : "instant",
			});
		},
		scrollTo(pos: number, smooth = false) {
			wrapperEl?.scrollTo({
				top: pos,
				behavior: smooth ? "smooth" : "instant",
			});
		},
		getOffset(id: string) {
			const idx = options.items().findIndex((x) => x.id === id);
			return idx !== -1 ? (offsets()[idx] ?? 0) : null;
		},
		getViewportHeight() {
			return wrapperEl?.clientHeight ?? 0;
		},
		List(
			listProps: { children: (item: T, idx: Accessor<number>) => JSX.Element },
		) {
			createEffect(on(options.items, onItemsChange));
			onCleanup(() => ro.disconnect());

			return (
				<ul
					class="list"
					ref={(el) => {
						wrapperEl = el;
					}}
					onScroll={onScroll}
					style="position: relative; overflow-y: scroll;"
				>
					{/* Explicitly setting the height so `scrollHeight` registers correctly */}
					<div
						style={`width: 100%; position: relative; height: ${totalHeight()}px;`}
					>
						<div
							ref={(el) => {
								containerEl = el;
							}}
							style="position: absolute; left: 0; right: 0; top: 0;"
						>
							<For
								each={options.items().slice(
									visibleRange().start,
									visibleRange().end + 1,
								)}
							>
								{(item) => {
									let wrapEl!: HTMLDivElement;

									createEffect(() => {
										if (!wrapEl) return;
										const globalIdx = options.items().findIndex((x) =>
											x.id === item.id
										);
										wrapEl.style.translate = `0 ${offsets()[globalIdx] ?? 0}px`;
										wrapEl.dataset.idx = String(globalIdx);
									});

									return (
										<div
											class="list-inner"
											classList={{ [item?.class ?? ""]: !!item?.class }}
											ref={(el) => {
												wrapEl = el;
												el.dataset.id = item.id;
												el.style.position = "absolute";
												el.style.left = "0";
												el.style.right = "0";
												ro.observe(el);
												onCleanup(() => ro.unobserve(el));
											}}
										>
											{listProps.children(
												item,
												() =>
													options.items().findIndex((x) => x.id === item.id),
											)}
										</div>
									);
								}}
							</For>
						</div>
					</div>
				</ul>
			);
		},
	};
}
