import { createResource, Show, VoidProps } from "solid-js";
import { generatePfp, pfpsLoaded } from "../pfp";
import { getThumbFromId } from "../media/util";
import { Room } from "sdk";

export const RoomIcon = (
	props: VoidProps<{ room: Room; pad?: number; mentionCount?: number }>,
) => {
	const size = 64;
	const pad = () => props.pad ?? 4;
	const totalSize = () => size + pad() * 2;
	const circPos = size - 4;
	const circRad = 12;
	const circPad = 6;

	const [pfp] = createResource(
		() => [props.room?.id, pfpsLoaded()],
		async ([roomId, loaded]) => {
			if (!roomId || !loaded) return "";
			// TODO: generated room icons
			return generatePfp(roomId);
		},
	);

	const mentionCount = () => props.mentionCount ?? 0;

	return (
		<svg
			class="avatar status-indicator"
			viewBox={`0 0 ${totalSize()} ${totalSize()}`}
			role="img"
			style={{ "--pad": `${pad()}px` }}
			classList={{ autogenerated: !props.room?.icon }}
		>
			{/* not sure if i want avatars to be boxes, circles, rounded boxes, ..? */}
			<mask id="rbox">
				<rect
					rx="6"
					width={size}
					height={size}
					x={pad()}
					y={pad()}
					fill="white"
				/>
				<circle cx={circPos} cy={circPos} r={circRad + circPad} fill="black" />
			</mask>
			<mask id="rbox2">
				<rect
					rx="6"
					width={size}
					height={size}
					x={pad()}
					y={pad()}
					fill="white"
				/>
			</mask>
			<g mask={mentionCount() > 0 ? "url(#rbox)" : "url(#rbox2)"}>
				<Show
					when={props.room?.icon}
					fallback={
						<image
							preserveAspectRatio="xMidYMid slice"
							width={size}
							height={size}
							x={pad()}
							y={pad()}
							href={pfp() ?? ""}
						/>
					}
				>
					<rect
						width={size}
						height={size}
						x={pad()}
						y={pad()}
						fill="oklch(var(--color-bg3))"
					/>
					<image
						// temp? i need to crop avatars properly on upload
						preserveAspectRatio="xMidYMid slice"
						width={size}
						height={size}
						x={pad()}
						y={pad()}
						href={getThumbFromId(props.room!.icon!)!}
					/>
				</Show>
			</g>
			<Show when={mentionCount() > 0}>
				<circle
					class="mention-count"
					cx={circPos}
					cy={circPos}
					r={circRad}
					fill="oklch(54.03% 0.1759 13.16)"
				/>
				<text
					x={circPos}
					y={circPos}
					text-anchor="middle"
					dominant-baseline="central"
					font-size="16"
					font-weight="bold"
					fill="white"
				>
					{mentionCount() > 99 ? "99+" : mentionCount()}
				</text>
			</Show>
		</svg>
	);
};
