import { createResource, Show, VoidProps } from "solid-js";
import { generatePfp, pfpsLoaded } from "../pfp";
import { getThumbFromId } from "../media/util";
import { User } from "sdk";

type AvatarProps = {
	user?: User;
	pad?: number;
	// room_member?: RoomMember,
	// thread_member?: ThreadMember,
};

export const AvatarWithStatus = (props: VoidProps<AvatarProps>) => {
	const size = 64;
	const pad = () => props.pad ?? 4;
	const totalSize = () => size + pad() * 2;
	const circPos = size;
	const circRad = 8;
	const circPad = 6;

	const [pfp] = createResource(
		() => [props.user?.id, pfpsLoaded()],
		async ([userId, loaded]) => {
			if (!userId || !loaded) return "";
			return generatePfp(userId);
		},
	);

	return (
		<svg
			class="avatar status-indicator"
			data-status={props.user?.presence.status ?? "Offline"}
			viewBox={`0 0 ${totalSize()} ${totalSize()}`}
			role="img"
			style={{ "--pad": `${pad()}px` }}
			classList={{ autogenerated: !props.user?.avatar }}
		>
			{/* not sure if i want avatars to be boxes, circles, rounded boxes, ..? */}
			<mask id="rbox">
				<rect
					rx="6"
					width={size}
					height={size}
					x={pad()}
					y={pad()}
					fill="white"
				/>
				<circle cx={circPos} cy={circPos} r={circRad + circPad} fill="black" />
			</mask>
			<g mask="url(#rbox)">
				<Show
					when={props.user?.avatar}
					fallback={
						<image
							preserveAspectRatio="xMidYMid slice"
							width={size}
							height={size}
							x={pad()}
							y={pad()}
							href={pfp() ?? ""}
						/>
					}
				>
					<rect
						width={size}
						height={size}
						x={pad()}
						y={pad()}
						fill="oklch(var(--color-bg3))"
					/>
					<image
						// temp? i need to crop avatars properly on upload
						preserveAspectRatio="xMidYMid slice"
						width={size}
						height={size}
						x={pad()}
						y={pad()}
						href={getThumbFromId(props.user!.avatar!)!}
					/>
				</Show>
			</g>
			<circle class="indicator" cx={circPos} cy={circPos} r={circRad} />
		</svg>
	);
};

export const Avatar = (props: VoidProps<AvatarProps>) => {
	const size = 64;
	const pad = () => props.pad ?? 4;
	const totalSize = () => size + pad() * 2;

	const [pfp] = createResource(
		() => [props.user?.id, pfpsLoaded()],
		async ([userId, loaded]) => {
			if (!userId || !loaded) return "";
			return generatePfp(userId);
		},
	);

	return (
		<svg
			class="avatar"
			data-status={props.user?.presence.status ?? "Offline"}
			viewBox={`0 0 ${totalSize()} ${totalSize()}`}
			role="img"
			style={{ "--pad": `${pad()}px` }}
			classList={{ autogenerated: !props.user?.avatar }}
		>
			{/* not sure if i want avatars to be boxes, circles, rounded boxes, ..? */}
			<mask id="rbox2">
				<rect
					rx="6"
					width={size}
					height={size}
					x={pad()}
					y={pad()}
					fill="white"
				/>
			</mask>
			<g mask="url(#rbox2)">
				<Show
					when={props.user?.avatar}
					fallback={
						<image
							preserveAspectRatio="xMidYMid slice"
							width={size}
							height={size}
							x={pad()}
							y={pad()}
							href={pfp() ?? ""}
						/>
					}
				>
					<rect
						width={size}
						height={size}
						x={pad()}
						y={pad()}
						fill="oklch(var(--color-bg3))"
					/>
					<image
						// temp? i need to crop avatars properly on upload
						preserveAspectRatio="xMidYMid slice"
						width={size}
						height={size}
						x={pad()}
						y={pad()}
						href={getThumbFromId(props.user!.avatar!)!}
					/>
				</Show>
			</g>
		</svg>
	);
};
