import type { User, UserStatus } from "sdk";
import {
	createResource,
	createUniqueId,
	Match,
	Show,
	Switch,
	type VoidProps,
} from "solid-js";
import { generatePfp, pfpsLoaded } from "@/lib/pfp";
import { getThumbFromId } from "@/media/util";

export type AvatarProps = {
	user?: User;
	pad?: number;
	animate?: boolean;
	style?: string;
	// room_member?: RoomMember,
	// thread_member?: ThreadMember,
	// TODO: pad?: boolean for <Avatar> (but not <AvatarWithStatus>) to disable padding
};

const getStatusPath = (status: UserStatus) => {
	const cx = 64;
	const cy = 64;
	const r = 12;

	switch (status) {
		case "Away": {
			const sweep = 2;
			return `M ${cx} ${cy - r} a ${r} ${r} 0 1 1 ${-r} ${r} a ${sweep} ${sweep} 0 0 0 ${r} ${-r} Z`;
		}

		case "Busy": {
			const s = 3;
			const w = r;
			const h = s * 2;
			return `M ${cx} ${cy - r} a ${r} ${r} 0 1 1 0 ${r * 2} a ${r} ${r} 0 1 1 0 -${r * 2} Z M ${cx - w / 2} ${cy - s} h ${w} a ${s} ${s} 0 0 1 0 ${h} h ${-w} a ${s} ${s} 0 0 1 0 ${-h} Z`;
		}

		case "Offline": {
			const s = 6;
			const i = r - s;
			return `M ${cx} ${cy - r} a ${r} ${r} 0 1 1 0 ${r * 2} a ${r} ${r} 0 1 1 0 -${r * 2} Z M ${cx} ${cy - r + s} a ${i} ${i} 0 1 1 0 ${i * 2} a ${i} ${i} 0 1 1 0 -${i * 2} Z`;
		}

		case "Online":
		default: {
			return `M ${cx} ${cy - r} a ${r} ${r} 0 1 1 0 ${r * 2} a ${r} ${r} 0 1 1 0 -${r * 2} Z`;
		}
	}
};

export const AvatarWithStatus = (props: VoidProps<AvatarProps>) => {
	const size = 64;
	const circPos = size;
	const circRad = 12;
	const circPad = 8;
	const pad = () => props.pad ?? 8;
	const totalSize = () => size + pad() * 2;

	const [pfp] = createResource(
		() => [props.user?.id, pfpsLoaded()],
		async ([userId, loaded]) => {
			if (!userId || !loaded) return "";
			return generatePfp(userId as string);
		},
	);

	const id = createUniqueId();
	const status = () => props.user?.presence.status ?? "Offline";

	// TODO: animate transitions between icons

	return (
		<svg
			aria-hidden="true"
			class="avatar status-indicator"
			data-status={status()}
			viewBox={`0 0 ${totalSize()} ${totalSize()}`}
			role="img"
			style={`--pad: ${pad()}px;` + (props.style ?? "")}
			classList={{ autogenerated: !props.user?.avatar }}
		>
			<defs>
				<mask id={`rbox-${id}`}>
					<rect
						rx="6"
						width={size}
						height={size}
						x={pad()}
						y={pad()}
						fill="white"
					/>
					<circle
						cx={circPos}
						cy={circPos}
						r={circRad + circPad}
						fill="black"
					/>
				</mask>
			</defs>
			<g mask={`url(#rbox-${id})`}>
				<Show
					when={props.user?.avatar}
					fallback={
						<image
							preserveAspectRatio="xMidYMid slice"
							width={size}
							height={size}
							x={pad()}
							y={pad()}
							href={pfp() ?? ""}
						/>
					}
				>
					{(avatar) => (
						<>
							<rect
								width={size}
								height={size}
								x={pad()}
								y={pad()}
								fill="oklch(var(--color-bg3))"
							/>
							<image
								// temp? i need to crop avatars properly on upload
								preserveAspectRatio="xMidYMid slice"
								width={size}
								height={size}
								x={pad()}
								y={pad()}
								href={getThumbFromId(avatar(), 64, props.animate)}
							/>
						</>
					)}
				</Show>
			</g>
			<path class="indicator" d={getStatusPath(status())} />
		</svg>
	);
};

export const Avatar = (props: VoidProps<AvatarProps>) => {
	const size = 64;
	const pad = () => props.pad ?? 4;
	const totalSize = () => size + pad() * 2;

	const [pfp] = createResource(
		() => [props.user?.id, pfpsLoaded()],
		async ([userId, loaded]) => {
			if (!userId || !loaded) return "";
			return generatePfp(userId as string);
		},
	);

	return (
		<svg
			aria-hidden="true"
			class="avatar"
			data-status={props.user?.presence?.status ?? "Offline"}
			viewBox={`0 0 ${totalSize()} ${totalSize()}`}
			role="img"
			style={`--pad: ${pad()}px; ${props.style ?? ""}`}
			classList={{ autogenerated: !props.user?.avatar }}
		>
			<defs>
				<mask id="rbox2">
					<rect
						rx="6"
						width={size}
						height={size}
						x={pad()}
						y={pad()}
						fill="white"
					/>
				</mask>
			</defs>
			<g mask="url(#rbox2)">
				<Show
					when={props.user?.avatar}
					fallback={
						<image
							preserveAspectRatio="xMidYMid slice"
							width={size}
							height={size}
							x={pad()}
							y={pad()}
							href={pfp() ?? ""}
						/>
					}
				>
					{(avatar) => (
						<>
							<rect
								width={size}
								height={size}
								x={pad()}
								y={pad()}
								fill="oklch(var(--color-bg3))"
							/>
							<image
								// temp? i need to crop avatars properly on upload
								preserveAspectRatio="xMidYMid slice"
								width={size}
								height={size}
								x={pad()}
								y={pad()}
								href={getThumbFromId(avatar(), 64, props.animate)}
							/>
						</>
					)}
				</Show>
			</g>
		</svg>
	);
};
