use lamprey_macros::endpoint;

use crate::v1::types::{oauth::Scope, Permission};

mod prelude {
    // pub use lamprey_macros::{request, response, route};
}

/// Error type for path parameter extraction
#[derive(Debug)]
pub struct PathParamError(pub String);

impl From<PathParamError> for http::Response<bytes::Bytes> {
    fn from(err: PathParamError) -> Self {
        http::Response::builder()
            .status(http::StatusCode::BAD_REQUEST)
            .body(bytes::Bytes::from(err.0))
            .unwrap()
    }
}

/// Trait for types that can be parsed from a path parameter string
pub trait PathParam: Sized {
    fn from_str(s: &str) -> Result<Self, PathParamError>;
}

impl PathParam for String {
    fn from_str(s: &str) -> Result<Self, PathParamError> {
        Ok(s.to_string())
    }
}

impl PathParam for i64 {
    fn from_str(s: &str) -> Result<Self, PathParamError> {
        s.parse()
            .map_err(|_| PathParamError(format!("invalid i64: {}", s)))
    }
}

impl PathParam for i32 {
    fn from_str(s: &str) -> Result<Self, PathParamError> {
        s.parse()
            .map_err(|_| PathParamError(format!("invalid i32: {}", s)))
    }
}

impl PathParam for u64 {
    fn from_str(s: &str) -> Result<Self, PathParamError> {
        s.parse()
            .map_err(|_| PathParamError(format!("invalid u64: {}", s)))
    }
}

impl PathParam for u32 {
    fn from_str(s: &str) -> Result<Self, PathParamError> {
        s.parse()
            .map_err(|_| PathParamError(format!("invalid u32: {}", s)))
    }
}

/// Metadata describing an API endpoint.
///
/// This struct is generated by the `#[endpoint]` macro and contains
/// routing and authorization information for the endpoint.
pub struct Endpoint {
    /// One line description of what this endpoint does.
    pub summary: &'static str,

    /// A more comprehensive description of this endpoint.
    pub description: Option<&'static str>,

    /// The HTTP method used by this endpoint.
    pub method: EndpointMethod,

    /// The URL path pattern for this endpoint (e.g., `/user/{id}`).
    pub path: &'static str,

    /// Tags used for documentation grouping and organization (user-provided only).
    pub tags: &'static [&'static str],

    /// All tags including badge tags (e.g., `badge.scope.Identify`).
    pub tags_full: &'static [&'static str],

    /// Required OAuth scopes for accessing this endpoint.
    pub scopes: &'static [Scope],

    /// Required permissions for accessing this endpoint.
    pub permissions: &'static [Permission],

    /// Optional permissions that may enhance functionality but are not required.
    pub permissions_optional: &'static [Permission],

    /// Required server permissions for accessing this endpoint.
    pub permissions_server: &'static [Permission],

    /// Optional server permissions that may enhance functionality but are not required.
    pub permissions_server_optional: &'static [Permission],
}

/// HTTP method for an endpoint.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EndpointMethod {
    Get,
    Post,
    Put,
    Patch,
    Delete,
    Head,
}

/// User get 2
///
/// Get another user, including your relationship
#[endpoint(
    get,
    path = "/user2/{user_id}",
    tags = ["user"],
    scopes = [Identify],
    response(OK, body = UserWithRelationship, description = "success"),
    errors(UnknownUser),
)]
pub mod user_get2 {
    use crate::v1::types::{misc::UserIdReq, UserWithRelationship};

    pub struct Request {
        /// the user id
        #[path]
        pub user_id: UserIdReq,
    }

    pub struct Response {
        #[json]
        pub user: UserWithRelationship,
    }
}
