use crate::v1::types::{oauth::Scope, Permission};

// export all routes

pub mod ack;
pub mod application;
pub mod auth;
pub mod automod;
pub mod calendar;
pub mod channel;
pub mod dm;
pub mod document;
pub mod emoji;
pub mod federation;
pub mod invite;
pub mod message;
pub mod moderation;
pub mod notification;
pub mod oauth;
pub mod permission_overwrite;
pub mod preferences;
pub mod push;
pub mod reaction;
pub mod relationship;
pub mod role;
pub mod room;
pub mod room_analytics;
pub mod room_member;
pub mod room_template;
pub mod search;
pub mod server;
pub mod session;
pub mod tag;
pub mod thread;
pub mod user;
pub mod user_connection;
pub mod user_email;
pub mod voice;
pub mod webhook;

pub use ack::*;
pub use application::*;
pub use auth::*;
pub use automod::*;
pub use calendar::*;
pub use channel::*;
pub use dm::*;
pub use document::*;
pub use emoji::*;
pub use federation::*;
pub use invite::*;
pub use message::*;
pub use moderation::*;
pub use notification::*;
pub use oauth::*;
pub use permission_overwrite::*;
pub use preferences::*;
pub use push::*;
pub use reaction::*;
pub use relationship::*;
pub use role::*;
pub use room::*;
pub use room_analytics::*;
pub use room_member::*;
pub use room_template::*;
pub use search::*;
pub use server::*;
pub use session::*;
pub use tag::*;
pub use thread::*;
pub use user::*;
pub use user_connection::*;
pub use user_email::*;
pub use voice::*;
pub use webhook::*;

mod path_param;

pub use path_param::{PathParam, PathParamError};

/// Create an error response for invalid path matches
pub fn invalid_path_error() -> http::Response<bytes::Bytes> {
    http::Response::builder()
        .status(http::StatusCode::NOT_FOUND)
        .body(bytes::Bytes::from("invalid path"))
        .unwrap()
}

/// Metadata describing an API endpoint.
///
/// This struct is generated by the `#[endpoint]` macro and contains
/// routing and authorization information for the endpoint.
pub struct Endpoint {
    /// One line description of what this endpoint does.
    pub summary: &'static str,

    /// A more comprehensive description of this endpoint.
    pub description: Option<&'static str>,

    /// The HTTP method used by this endpoint.
    pub method: EndpointMethod,

    /// The URL path pattern for this endpoint (e.g., `/user/{id}`).
    pub path: &'static str,

    /// Tags used for documentation grouping and organization (user-provided only).
    pub tags: &'static [&'static str],

    /// All tags including badge tags (e.g., `badge.scope.Identify`).
    pub tags_full: &'static [&'static str],

    /// Required OAuth scopes for accessing this endpoint.
    pub scopes: &'static [Scope],

    /// Required permissions for accessing this endpoint.
    pub permissions: &'static [Permission],

    /// Optional permissions that may enhance functionality but are not required.
    pub permissions_optional: &'static [Permission],

    /// Required server permissions for accessing this endpoint.
    pub permissions_server: &'static [Permission],

    /// Optional server permissions that may enhance functionality but are not required.
    pub permissions_server_optional: &'static [Permission],
}

/// HTTP method for an endpoint.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EndpointMethod {
    Get,
    Post,
    Put,
    Patch,
    Delete,
    Head,
}

impl From<EndpointMethod> for ::utoipa::openapi::HttpMethod {
    fn from(m: EndpointMethod) -> Self {
        match m {
            EndpointMethod::Get => ::utoipa::openapi::HttpMethod::Get,
            EndpointMethod::Post => ::utoipa::openapi::HttpMethod::Post,
            EndpointMethod::Put => ::utoipa::openapi::HttpMethod::Put,
            EndpointMethod::Patch => ::utoipa::openapi::HttpMethod::Patch,
            EndpointMethod::Delete => ::utoipa::openapi::HttpMethod::Delete,
            EndpointMethod::Head => ::utoipa::openapi::HttpMethod::Head,
        }
    }
}
