alter type permission rename value 'ThreadManage' to 'ThreadEdit';
alter type permission rename value 'ThreadCreate' to 'ThreadCreateChat';
alter type permission rename value 'MessageFilesEmbeds' to 'MessageAttachments';

alter type permission add value 'BotsAdd';
alter type permission add value 'BotsManage';
alter type permission add value 'EmojiAdd';
alter type permission add value 'EmojiManage';
alter type permission add value 'EmojiUseExternal';
alter type permission add value 'MemberBanManage';
alter type permission add value 'MemberBridge';
alter type permission add value 'MessageEmbeds';
alter type permission add value 'MessageMove';
alter type permission add value 'MessageReactionAdd';
alter type permission add value 'ProfileAvatar';
alter type permission add value 'ProfileOverride';
alter type permission add value 'ServerAdmin';
alter type permission add value 'ServerMetrics';
alter type permission add value 'ServerOversee';
alter type permission add value 'ServerReports';
alter type permission add value 'TagApply';
alter type permission add value 'TagManage';
alter type permission add value 'ThreadArchive';
alter type permission add value 'ThreadCreateDocument';
alter type permission add value 'ThreadCreateEvent';
alter type permission add value 'ThreadCreateForumLinear';
alter type permission add value 'ThreadCreateForumTree';
alter type permission add value 'ThreadCreateTable';
alter type permission add value 'ThreadCreateVoice';
alter type permission add value 'ThreadCreatePublic';
alter type permission add value 'ThreadCreatePrivate';
alter type permission add value 'ThreadForward';
alter type permission add value 'ThreadLock';
alter type permission add value 'ThreadPin';
alter type permission add value 'ThreadPublish';
alter type permission add value 'UserDms';
alter type permission add value 'UserProfile';
alter type permission add value 'UserSessions';
alter type permission add value 'UserStatus';
alter type permission add value 'ViewAuditLog';
alter type permission add value 'VoiceConnect';
alter type permission add value 'VoiceDeafen';
alter type permission add value 'VoiceDisconnect';
alter type permission add value 'VoiceMove';
alter type permission add value 'VoiceMute';
alter type permission add value 'VoicePriority';
alter type permission add value 'VoiceSpeak';
alter type permission add value 'VoiceVideo';
