# example config for the discord bridge

rust_log = "debug"
lamprey_base_url = "https://example.com"
lamprey_ws_url = "wss://example.com"
lamprey_cdn_url = "https://example-cdn.com"
lamprey_token = "secret"
discord_token = "secret"
database_url = "sqlite:///data/data.db"
